# Here we define the name of our workflow
name: Hello world

# Here we define how the workflow should be executed
on:
  push:
    branches:
      - main

# And here we define the steps that the workflow should execute
jobs:
  hello-world:
    # Now we define the runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"

      - name: Test
        # We can use multiple lines
        run: |
          ls -all
          echo "Hello world"
